pipeline {
    agent {label "linux"}
    stages {
        stage('Hello') {
            steps {
                echo "Hello, world!"
            }
        }
        stage('for the fix branch') {
            when {
                branch "fix-*"
            }
            steps {
                sh '''
                cat README.md
                '''
            }
        }
        stage('for the pull request') {
            when {
                branch 'PR-*'
            }
            steps {
                echo "This is only for Pull requests"
            }
        }
    }
}